[package]
name = "oag-tools"
description = "Command line tools for inspecting and extracting Wipeout game data"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "oag-unpack"
path = "src/bin/oag-unpack.rs"

[[bin]]
name = "oag-wad"
path = "src/bin/oag-wad.rs"

[dependencies]
oag-assets.workspace = true
oag-disc.workspace = true
oag-formats.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
