#!/usr/bin/env python3
"""Generate the "RE coverage per binary" table in docs/overview/status.md.

The table is derived, never hand-edited: every number comes out of
`docs/ghidra/functions/<binary>/names.tsv` and the evidence pages beside it,
so it cannot drift from the files it describes the way a maintained list
did. The block sits between two HTML comment markers in status.md; this
script rewrites what is between them and leaves the rest of the page alone.

    python3 scripts/gen-re-coverage.py          # rewrite the block in place
    python3 scripts/gen-re-coverage.py --check  # exit 1 if the block is stale

`just gen-status` runs the first form, `just check-status` (part of the
default gate) the second, so a names.tsv row landing without the table moving
fails CI rather than review.

What each column is:

- names.tsv rows: non-comment, non-empty rows, split function/data.
- `_q` share: rows whose confidence is below 70 (the suffix is derived from
  the confidence column, never written - see CLAUDE.md), i.e. names that
  are still hypotheses.
- evidence pages: `*.md` files in the directory other than README.md.
- harness: the emulator drive/trace/debugger scripts under scripts/ whose
  prefix matches the platform (`psp-`/`ppsspp_`, `pcsx2`, `rpcs3`, `vita-`),
  named individually; the one-off measurement scripts beside them (a mine
  count, a clamp check) are counted, not listed. Omega has none and needs
  none - native x86-64 loads without a processor module.
- last dated finding: the newest `YYYY-MM-DD` mentioned anywhere on the
  binary's pages, and the page it is on. The date is derivable; what the
  finding *was* is not, so the cell links the page instead of summarising.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FUNCTIONS = ROOT / "docs" / "ghidra" / "functions"
STATUS = ROOT / "docs" / "overview" / "status.md"
SCRIPTS = ROOT / "scripts"
BEGIN = "<!-- re-coverage:begin - generated by scripts/gen-re-coverage.py, do not edit by hand -->"
END = "<!-- re-coverage:end -->"

# The harness scripts are grouped by the platform prefix their names carry.
# A script is "the harness" when its name carries one of these; the rest of a
# platform's scripts are one-off measurements and only counted.
HARNESS_WORDS = ("drive", "trace", "debugger", "pine", "dump", "gxp", "self-decrypt", "loader")

HARNESS_PREFIXES = {
    "psp-": ("psp-", "ppsspp_", "psp_"),
    "ps2-": ("pcsx2",),
    "ps3-": ("rpcs3",),
    "vita-": ("vita-",),
    "ps4-": (),
}

DATE = re.compile(r"\b(20\d\d-\d\d-\d\d)\b")


def harness_for(binary: str) -> str:
    for prefix, script_prefixes in HARNESS_PREFIXES.items():
        if binary.startswith(prefix):
            names = sorted(
                p.name
                for p in SCRIPTS.iterdir()
                if p.suffix in (".py", ".sh") and p.name.startswith(script_prefixes)
            )
            if not names:
                return "none"
            core = [n for n in names if any(w in n for w in HARNESS_WORDS)]
            rest = len(names) - len(core)
            cell = ", ".join(f"`{n}`" for n in core) or "none"
            if rest:
                cell += f" (+{rest} measurement script{'s' if rest != 1 else ''})"
            return cell
    return "none"


def coverage_row(directory: Path) -> str:
    binary = directory.name
    functions = data = low = 0
    tsv = directory / "names.tsv"
    if tsv.exists():
        for line in tsv.read_text(encoding="utf-8").splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) < 4:
                continue
            kind = fields[1]
            functions += kind == "function"
            data += kind == "data"
            try:
                low += int(fields[3]) < 70
            except ValueError:
                pass
    total = functions + data
    pages = sorted(p for p in directory.glob("*.md") if p.name != "README.md")
    newest: tuple[str, str] | None = None
    for page in pages + ([directory / "README.md"] if (directory / "README.md").exists() else []):
        for match in DATE.finditer(page.read_text(encoding="utf-8", errors="replace")):
            if newest is None or match.group(1) > newest[0]:
                newest = (match.group(1), page.name)
    low_cell = f"{low} ({low * 100 // total}%)" if total else "0"
    if newest:
        last = f"{newest[0]}, [{newest[1]}]({directory.relative_to(STATUS.parent, walk_up=True)}/{newest[1]})"
    else:
        last = "undated"
    rel = directory.relative_to(STATUS.parent, walk_up=True)
    return (
        f"| [{binary}]({rel}/) | {total} ({functions} fn, {data} data) | {low_cell} "
        f"| {len(pages)} | {harness_for(binary)} | {last} |"
    )


def render() -> str:
    dirs = sorted(d for d in FUNCTIONS.iterdir() if d.is_dir())
    lines = [
        BEGIN,
        "",
        "| Binary | names.tsv rows | below 70 (`_q`) | Evidence pages | Emulator harness | Newest dated page |",
        "| --- | ---: | ---: | ---: | --- | --- |",
    ]
    lines += [coverage_row(d) for d in dirs]
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < 0:
        sys.exit(f"{STATUS}: markers {BEGIN!r} / {END!r} not found")
    return text[:start] + block + text[end + len(END) :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the block is stale")
    args = parser.parse_args()
    current = STATUS.read_text(encoding="utf-8")
    updated = splice(current, render())
    if args.check:
        if updated != current:
            print(
                f"{STATUS.relative_to(ROOT)}: RE coverage table is stale - run `just gen-status`",
                file=sys.stderr,
            )
            return 1
        print("OK: RE coverage table matches names.tsv and the evidence pages")
        return 0
    if updated != current:
        STATUS.write_text(updated, encoding="utf-8")
        print(f"rewrote the RE coverage block in {STATUS.relative_to(ROOT)}")
    else:
        print("RE coverage block already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
